[package]
name = "flatten"
version = "0.1.0"
authors = ["Scott.Simpson"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rayon = "1.3.0"
num_cpus = "1.0"
ctrlc = "3.1.4"
clap = "3.0.0-beta.2"